# Audio configuration
PHRASE_TIME_LIMIT = 4.0
VAD_PAUSE_THRESHOLD = 0.6
ENERGY_THRESHOLD = 150
NON_SPEAKING_DURATION = 0.4

# TODO: Finish refactoring
# TTS configuration
TTS_VOICE = "en-US-GuyNeural"
TTS_ATOM_RATE = "+20%"
TTS_TARGET_SR = 24000
TTS_CROSSFADE_MS = 20.0
TTS_SILENCE_GAP_MS = 30.0
TTS_POST_GAP_MS = 100.0

TTS_CACHE_SIZE = 100
TTS_RATE = "+30%"
TTS_PREGEN_MOVES = 8 
BASE_DELAY = 0.4
PER_WORD_DELAY = 0.1

# UI configuration
BOARD_SQUARE_SIZE = 80
BOARD_SIZE = 640
BOARD_FPS = 60
LIGHT_SQUARE = (240, 217, 181)
DARK_SQUARE = (181, 136, 99)

# Engine configuration
DEFAULT_SKILL_LEVEL = 10
DEFAULT_THINK_TIME = 1.0
TIMEOUT_STOCKFISH = 360
